version: "3.7"

services:
  postgres:
    image: postgres:12.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=gobank
      - POSTGRES_PASSWORD=gobank
      - POSTGRES_DB=gobank
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always